### PR TITLE
installing special requirements before package

### PR DESCRIPTION
**Pull request by scarrazza**
Fixes failures such as https://github.com/qiboteam/qibojit/actions/runs/4794880505/jobs/8528754081

### CODE REVIEW

**Review by AleCandido — APPROVED** [review]
This should solve the issue, but: is there a reason why we keep installing `qibo` and `qibojit` from source, instead of using the PyPI released versions?

**Comment by scarrazza** [comment]
For this particular issue we are making changes in qibo and qibojit simultaneously. In this context it would be good to check the cross-compatibility between PRs before merging and making a new release of one of both components. So I believe that we should keep the ability of cloning the latest version before release.

**Comment by AleCandido** [comment]
> For this particular issue we are making changes in qibo and qibojit simultaneously. In this context it would be good to check the cross-compatibility between PRs before merging and making a new release of one of both components. So I believe that we should keep the ability of cloning the latest version before release.

Syncing PRs is not a great idea, it causes a significant overhead and spoils reproducibility (you rely on two unstable objects, and you have to keep them aligned).

Typical solutions to this problem are either developing loosely related tools, with a clear dependency (here is almost circular, even if not formally, since Qibojit depends on Qibo, but Qibo makes use of Qibojit...), and in this case we should mutually rely on releases, or a monorepo approach.

Poetry does not support monorepos out of the box, but it supports multiple Python packages (so-called "import packages") in a single PyPI package (alias "distribution package"), since `pip` does support them (and they are part of the official specs).
I.e. we can not make two independent `pyproject.toml` files with separate deps and metadata, and distribute two packages, but we could distribute Qibojit together with Qibo, simply making its dependencies optional, and installing with the usual `pip install qibo[jit]` (in any case, Qibojit deps, the only extra one would be Numba).

**Comment by scarrazza** [comment]
Indeed, this PR is not so bad because at the end it is fixing a install ordering bug, but I agree that the current layout is not optimal, at the moment if we change the backend API in qibo, we cannot afford a premature release or beta release just to test qibojit's upgrade.

**Pull request merged**
