### PR TITLE
Update Node version 

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
This PR has been opened in order to fix issue qiboteam/qibo#753 and to update all the actions' versions.

### CODE REVIEW

**Comment by AleCandido** [comment]
Unless strictly required, keep the version for each action with a single digit, i.e. `v1` and not `v1.0.7`. Usually they stick to the latest compatible version, so `v1 >= v1.0.7` (if `v1.0.7` exists) and `v1 < v2.x.y`, such that it is not going to silently break your workflow.

**Comment by scarrazza** [comment]
BTW, the issue was referring to all workflows not only those in this repository.

**Comment by AleCandido** [comment]
> BTW, the issue was referring to all workflows not only those in this repository.

I would try to address the rest of the issue during the migration to this repo. However, only if it is not taking too long.

**Review by AleCandido — APPROVED** [review]
It does not close the issue, but it updates workflows in this repo

**Review by scarrazza — APPROVED** [review]

**Pull request merged**
